### ISSUE TITLE
Error using stable-diffusion v1.5

### ISSUE THREAD

**Issue by matemato** [magic-research/LightningDrag#3]
Hi, great work!

I wanted to use a mirror of the [stable diffusion 1.5 model ](https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5), but I get this error when I press run drag.

`RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[8, 9, 72, 56] to have 4 channels, but got 9 channels instead`

Thank you so much for your work and help!

p.s. I'm doing a research project and I'm thinking of using these kind of pipelines for faces. Do you know where I could follow the latest info on the updates for research/articles about these new upcoming pipelines (drag-diffusion, good-drag, insta-drag, lightningDrag..)?

**Comment by liewjunhao** [comment]
Hi, sorry for the typo in README.md. It should be `stable-diffusion-inpainting` instead of `stable-diffusion-v1-5`. Unfortunately, since Runway has removed it from HuggingFace (https://github.com/huggingface/diffusers/issues/9421), you have to replace it with your own local checkpoint if you wish to try our original model.
